apiVersion: v1
kind: Service
metadata:
  name: redis-hits-counter
  labels:
    app: redis-hits-counter
    tier: frontend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30102
  selector:
    app: redis-hits-counter
    tier: frontend
  type: NodePort
