apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-hits-counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-hits-counter
        tier: frontend
    spec:
      containers:
      - name: redis-hits-counter
        image: dnabic/redis-hits-counter:v0.1.2
        ports:
        - containerPort: 5000
          protocol: TCP
